config/routes.rb
Rails.application.routes.draw do
  # user用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords"
  }

  # devise signout時のエラー解消
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise signup時のエラー解消
  get "users" => redirect("/users/sign_up")

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :posts do
      collection do
        get :dashboard
        get :analytics
        get :weekly_ranking
        get :trending
        post :preview
      end

      resource :post_favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        resource :comment_favorites, only: [:create, :destroy]
      end
    end
    resources :comments, only: [:update]
    resources :tags, only: [:show]
    resources :reports, only: [:new, :create]

    # URLをaccount名に変更
    resources :users, param: :account, only: [:show, :edit, :update] do
      member do
        # いいねした一覧
        get :liked_posts

        # 退会機能
        get :withdraw_input
        patch :withdraw_process

        # フォロー機能
        post :follow, to: "relationships#create"
        delete :unfollow, to: "relationships#destroy"
        get :follower_list
        get :following_list

      end

      # 急上昇ユーザー一覧ページ
      get :rising_users, on: :collection
    end

    resources :notifications, only: [:index] do
      post :update_checked, on: :collection
    end

  end

  get "/search", to: "searches#search", as: :search
  get "/search/results", to: "searches#search_results", as: :search_results

  post "/chatbots", to: "chatbots#create"


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # devise signout時のエラー解消
  devise_scope :admin do
    get "/admin/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    root to: "homes#top"
    resources :posts, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :users, only: [:index, :show, :update]
    resources :reports, only: [:show, :update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
  def self.search_all_models(content, model, method)
    if model.present?
      if model == "user"
        User.search_content(content, method)
      elsif model == "post"
        Post.search_content(content, method)
      elsif model == "tag"
        # タグの検索
        ActsAsTaggableOn::Tag.named_like(content)
      end
    else
      results = []
      results << User.search_content(content, method)
      results << Post.search_content(content, method)
      results << ActsAsTaggableOn::Tag.named_like(content)
      results.flatten
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
  end

  def search_results
    @content = params[:content]
    @model = params[:model] || "nil"
    @method = params[:method]

    if @content.blank?
      flash.now[:error] = "検索ワードを入力してください。"
      render "searches/search"
      return
    end

    if @model == "post"
      @results = Post.tagged_with(@content)
    elsif @model == "tag"
      @results = ActsAsTaggableOn::Tag.named_like(@content).order(:name)
    end

    # Array
    @results = Search.search_all_models(@content, @model, @method)
    @results = @results.order(created_at: :desc).page(params[:page]).per(12)
    @total_results_count = @results.total_count


    render "searches/search_results"
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2 mt-5">
      <%= form_with url: search_results_path, method: :get, local: true do |f| %>
        <!-- modelのラジオボタン -->
        <div class="mb-3">
          <div class="form-check form-check-inline">
            <%= f.radio_button :model, "tag", class: "form-check-input", id: "tag_model", checked: true %>
            <%= f.label :model_tag, "タグ", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :model, "user", class: "form-check-input", id: "user_model" %>
            <%= f.label :model_user, "ユーザー", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :model, "post", class: "form-check-input", id: "post_model" %>
            <%= f.label :model_post, "投稿", class: "form-check-label" %>
          </div>
        </div>

        <!-- methodのラジオボタン -->
        <div class="mb-3">
          <div class="form-check form-check-inline">
            <input type="radio" name="method" value="partial" class="form-check-input" id="partial_method" checked="checked">
            <label for="partial_method" class="form-check-label">部分一致</label>
          </div>
          
          <div class="form-check form-check-inline">
            <input type="radio" name="method" value="perfect" class="form-check-input" id="perfect_method">
            <label for="perfect_method" class="form-check-label">完全一致</label>
          </div>
        </div>

        <!-- 検索キーワードと検索ボタン -->
        <div class="input-group mb-3">
          <%= f.text_field :content, class: "form-control", placeholder: "検索キーワード", autofocus: true %>
          <div class="input-group-append">
            <%= f.submit "検索", class: "btn btn-dark" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/search_results.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <% if @model == 'user' %>
        <h4 class="headline">Users search for "<%= @content %>"（<%= @total_results_count %>件）</h4>
        <% if @results.present? %>
          <% @results.each do |user| %>
            <%= render partial: 'public/users/profile-card', locals: { user: user }  %>
          <% end %>
        <% else %>
          <p>ユーザーの検索結果がありません</p>
        <% end %>
      <% elsif @model == 'post' %>
        <h4 class="headline">Posts search for "<%= @content %>"（<%= @total_results_count %>件）</h4>
        <% if @results.present? %>
          <%= render partial: 'public/posts/index', locals: { posts: @results }  %>
        <% else %>
          <p>投稿の検索結果がありません</p>
        <% end %>
      <% elsif @model == 'tag' %>
        <h4 class="headline">Tags search for "<%= @content %>"</h4>
        <% if @results.present? %>
          <% @results.each do |tag| %>
            <%= render partial: 'public/shared/tag_post', locals: { results: @results } %>
          <% end %>
        <% else %>
          <p>タグの検索結果がありません</p>
        <% end %>
      <% else %>
        <h3>Search for "<%= @content %>"</h3>
        <% if @results.present? %>
          <% @results.each do |result| %>
            <% if result.is_a?(User) %>
              <h4>User</h4>
              <%= render partial: 'public/users/shared/profile-card', locals: { user: result } %>
            <% elsif result.is_a?(Post) %>
              <h4>Post</h4>
              <%= render partial: 'public/posts/index', locals: { posts: [result] } %>
            <% end %>
          <% end %>
        <% else %>
          <p>検索結果がありません</p>
        <% end %>
      <% end %>
      <div class="pagination justify-content-center">
        <%= paginate @results, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>