config/routes.rb
Rails.application.routes.draw do
  # user用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords"
  }

  # devise signout時のエラー解消
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise signup時のエラー解消
  get "users" => redirect("/users/sign_up")

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :posts do
      collection do
        get :dashboard
        get :analytics
        get :weekly_ranking
        get :trending
        post :preview
      end

      resource :post_favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        resource :comment_favorites, only: [:create, :destroy]
      end
    end
    resources :comments, only: [:update]
    resources :tags, only: [:show]
    resources :reports, only: [:new, :create]

    # URLをaccount名に変更
    resources :users, param: :account, only: [:show, :edit, :update] do
      member do
        # いいねした一覧
        get :liked_posts

        # 退会機能
        get :withdraw_input
        patch :withdraw_process

        # フォロー機能
        post :follow, to: "relationships#create"
        delete :unfollow, to: "relationships#destroy"
        get :follower_list
        get :following_list

      end

      # 急上昇ユーザー一覧ページ
      get :rising_users, on: :collection
    end

    resources :notifications, only: [:index] do
      post :update_checked, on: :collection
    end

  end

  get "/search", to: "searches#search", as: :search
  get "/search/results", to: "searches#search_results", as: :search_results

  post "/chatbots", to: "chatbots#create"


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # devise signout時のエラー解消
  devise_scope :admin do
    get "/admin/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    root to: "homes#top"
    resources :posts, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :users, only: [:index, :show, :update]
    resources :reports, only: [:show, :update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "User", foreign_key: "reporter_id"
  belongs_to :reported, class_name: "User", foreign_key: "reported_id"
  belongs_to :content, polymorphic: true
  
  # reporter_idがuser_idである通報の件数を返すクラスメソッド
  def self.reported_count(user_id)
    where(reported_id: user_id).count
  end
  
  enum reason: {
    malicious_expression: 0,
    inappropriate_content: 1,
    misinformation: 2,
    commercial_purposes: 3,
    spam: 4,
    other: 5
  }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @report =  Report.find(params[:id])
  end

  def update
    Report.find(params[:id]).update(report_params)
    redirect_to request.referer, notice: "ステータスを更新しました。"
  end
  
  private

  def report_params
    params.require(:report).permit(:is_checked) 
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_index.html.erb
<div class="container mt-5">
  <%= link_to "会員一覧へ",admin_users_path,class: "btn btn-primary " %>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">通報一覧</h3>
      ※番号から通報詳細へ飛びます。
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>通報ID</th>
              <th>通報日</th>
              <th>会員名</th>
              <th>通報者</th>
              <th>通報された回数</th>
              <th>管理者check</th>
            </tr>
          </thead>
          <tbody>
            <% @reports.each do |report| %>
              <tr>
                <td><%= link_to report.id, admin_report_path(report) %></td>
                <td><%= report.created_at.in_time_zone('Tokyo').strftime('%Y-%m-%d %H:%M:%S') %></td>
                <td><%= report.reported.nickname %></td>
                <td><%= report.reporter.nickname %></td>
                <td><%= Report.where(reported_id: report.reported_id).count %></td>
                <td>
                  <% if report.is_checked %>
                    <span class="badge badge-success">確認済み</span>
                  <% else %>
                    <span class="badge badge-danger">未確認</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="pagination justify-content-center">
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="card mx-auto mt-5" style="width: 500px;">
  <div class="card-body">
    <h3 class="card-title text-center">通報詳細</h3>
    <div class="row">
      <div class="col-6"><strong>通報ID</strong></div>
      <div class="col-6"><%= link_to @report.id %></div>
    </div>
    <div class="row">
      <div class="col-6"><strong>会員名</strong></div>
      <div class="col-6"><%= link_to @report.reported.nickname, admin_user_path(@report.reported_id) %></div>
    </div>
    <div class="row">
      <div class="col-6"><strong>理由</strong></div>
      <div class="col-6"><%= I18n.t("enums.report.reason.#{@report.reason}") %></div>
    </div>
    <div class="row">
      <div class="col-6"><strong>通報者</strong></div>
      <div class="col-6"><%= @report.reporter.nickname %></div>
    </div>
    <div class="row">
      <div class="col-6"><strong>対応ステータス</strong></div>
      <div class="col-6">
        <%= form_with model:@report, url:admin_report_path(@report), method: :patch, local: true do |f| %>
          <div class="form-group text-center">
            <%= f.select :is_checked, { "未確認": false, "確認済み": true }, {}, class: "form-control" %>
          </div>
          <%= f.submit '更新', class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "通報一覧へ", admin_root_path %>
  </div>
</div>