config/routes.rb
Rails.application.routes.draw do
  # user用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords"
  }

  # devise signout時のエラー解消
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise signup時のエラー解消
  get "users" => redirect("/users/sign_up")

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :posts do
      collection do
        get :dashboard
        get :analytics
        get :weekly_ranking
        get :trending
        post :preview
      end

      resource :post_favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        resource :comment_favorites, only: [:create, :destroy]
      end
    end
    resources :comments, only: [:update]
    resources :tags, only: [:show]
    resources :reports, only: [:new, :create]

    # URLをaccount名に変更
    resources :users, param: :account, only: [:show, :edit, :update] do
      member do
        # いいねした一覧
        get :liked_posts

        # 退会機能
        get :withdraw_input
        patch :withdraw_process

        # フォロー機能
        post :follow, to: "relationships#create"
        delete :unfollow, to: "relationships#destroy"
        get :follower_list
        get :following_list

      end

      # 急上昇ユーザー一覧ページ
      get :rising_users, on: :collection
    end

    resources :notifications, only: [:index] do
      post :update_checked, on: :collection
    end

  end

  get "/search", to: "searches#search", as: :search
  get "/search/results", to: "searches#search_results", as: :search_results

  post "/chatbots", to: "chatbots#create"


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # devise signout時のエラー解消
  devise_scope :admin do
    get "/admin/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    root to: "homes#top"
    resources :posts, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :users, only: [:index, :show, :update]
    resources :reports, only: [:show, :update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer text-center">
    <a href="https://github.com/Ganmo3">Github link: created by Ganmo3</a>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-D5G8K7RC7B"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-D5G8K7RC7B');
</script>

app/views/layouts/_header.html.erb
<header class="sticky-top" id="header">
  <nav class="navbar navbar-expand-sm navbar-expand-md navbar-expand-lg navbar-expand-xl">
    <div class="logo-container col-sm-2 col-2">
      <%= link_to root_path, data: { "turbolinks" => false } do %>
        <%= image_tag "logo_2seedsr1.png", alt: "LOGO", width: "60px", height: "auto" %>
      <% end %>
    </div>

    <div class="d-flex justify-content-end align-items-center flex-grow-1">
      <div class="search-container">
        <%= link_to search_path do %>
          <i class="fas fa-search fa-lg mr-3"></i>
        <% end %>
      </div>
    </div>

    <!-- サインインしている場合のメニュー要素（通常の表示） -->
    <% if user_signed_in? %>
      <div class="mypage-nav d-flex align-items-center">
        <div class="bell-container mr-3">
          <a href="javascript:void(0)" id="notifications-link">
            <% if unchecked_notifications.any? %>
              <span class="fa-stack" style="vertical-align: middle;">
                <i class="far fa-bell fa-lg fa-stack-1x" style="font-size: 1.5em;"></i>
                  <i class="fas fa-circle n-circle fa-stack-1x">
                    <span class="notification-count"><%= unchecked_notifications.count %></span>
                  </i>
              </span>
            <% else %>
              <i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i>
            <% end %>
          </a>
        </div>

        <!-- マイページへのリンクとユーザーアイコン -->
        <div class="mypage-btn-container" id="mypageBtnContainer">
          <%= user_icon_or_youtube(current_user, size: '40x40', class: 'rounded-circle cursor-pointer') %>
          <div class="mypage-dropdown" id="mypageDropdown">
            <ul>
              <li><%= link_to user_path(current_user), data: { "turbolinks" => false } do %><i class="fas fa-user-circle"></i>マイページ<% end %></li>
              <li><%= link_to new_post_path, data: { "turbolinks" => false } do %><i class="fas fa-pen"></i>新規投稿<% end %></li>
              <li><%= link_to dashboard_posts_path, data: { "turbolinks" => false } do %><i class="fas fa-clipboard-list"></i>ダッシュボード<% end %></li>
              <li><%= link_to analytics_posts_path, data: { "turbolinks" => false } do %><i class="fas fa-chart-line"></i>アナリティクス<% end %></li>
              <li><%= link_to edit_user_path(current_user), data: { "turbolinks" => false } do %><i class="fas fa-user-cog"></i>プロフィール設定<% end %></li>
              <li><%= link_to liked_posts_user_path(current_user), data: { "turbolinks" => false } do %><i class="fas fa-thumbs-up"></i>いいねした投稿<% end %></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="mypage-btn-container" id="navBtnContainer">
      <% unless user_signed_in? %>
        <div class="nav-btn" id="menuBtn">Menu▼</div>
        <div class="mypage-dropdown" id="navDropdown">
          <ul>
            <% if admin_signed_in? %>
              <li><%= link_to destroy_admin_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i>Log Out<% end %></li>
            <% else %>
              <% unless user_signed_in? %>
                <li><%= link_to new_user_registration_path do %><i class="fas fa-user-plus"></i>Sign Up<% end %></li>
                <li><%= link_to new_user_session_path do %><i class="fas fa-sign-in-alt"></i>Log In<% end %></li>
                <li><%= button_to users_guest_sign_in_path, method: :post, class: "guest-button" do %><i class="fas fa-glass-cheers"></i>Guest Login<% end %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>

  <!-- 通知一覧を表示するモーダルウィンドウ -->
  <div id="notifications-modal" class="modal">
    <div class="common-modal-content"></div>
    <button id="close-modal" class="close-button">×</button>
  </div>
</header>



<script>
  $(document).ready(function() {
    $('#notifications-link').click(function() {
      // 通知を確認済みに更新するアクションを呼び出す
      $.ajax({
        url: '<%= update_checked_notifications_path %>',
        type: 'POST',
        success: function() {
          $('.n-circle').removeClass('orange');
          $('#notifications-link').html('<i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i>');

          // 通知モーダルを表示する処理
          $.ajax({
            url: '<%= notifications_path(@user) %>',
            type: 'GET',
            success: function(response) {
              $('#notifications-modal .common-modal-content').html(response);
              $('#notifications-modal').addClass('fade-in').show();
            }
          });
        }
      });
    });

  // モーダル内のクリックイベントを停止
  $('#notifications-modal .modal-content').on('click', function(event) {
    event.stopPropagation(); // イベントの伝播を停止
  });

  // モーダル外（背景）をクリックしたときにモーダルを閉じる
  $('#notifications-modal').on('click', function() {
    $(this).addClass('fade-out');
    setTimeout(() => {
      $(this).hide().removeClass('fade-out');
    }, 300);
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwoSeeds</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>

    <script src="https://kit.fontawesome.com/5f9cac3054.js" crossorigin="anonymous"></script>
    <script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/master/dist/progressbar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= display_meta_tags(default_meta_tags)%>
  </head>

  <body>
    <% if @show_header %>
      <%= render 'layouts/header' %>
    <% end %>

     <a href="#top" class="scroll-top-btn">
      <i class="fas fa-chevron-circle-up" data-toggle=tooltip data-placement="bottom" title="最上部へ移動"></i>
    </a>
    <main>
      <%= content_tag :div, flash[:notice], class: "flash-message notice" if flash[:notice].present? %>
      <%= content_tag :div, flash[:alert], class: "flash-message alert" if flash[:alert].present? %>
      <%= content_tag :div, flash[:error], class: "flash-message error" if flash[:error].present? %>
      <%= content_tag :div, flash[:success], class: "flash-message success" if flash[:success].present? %>
      <div class="success-message"></div>

      <%= yield %>

      <%= render 'chatbots/chatbot' %>
      <button type="button" class="chatbot-btn" data-toggle="modal" data-target="#chat-modal">
        <i class="fas fa-robot" data-toggle=tooltip data-placement="bottom" title="ボットにゃんと遊ぶ！"></i>
      </button>
    </main>
    <% if @show_footer %>
      <%= render 'layouts/footer' %>
    <% end %>


    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </body>
</html>